---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-db-user
type: Opaque
data:
  DB_HOST: bXlzcWw=           # mysql
  DB_USER: aXJvbmlj           # ironic
  DB_DATABASE: aXJvbmlj       # ironic
  DB_PASSWORD: cGFzc3dvcmQ=   # password
---
apiVersion: v1
kind: Secret
metadata:
  name: "mysql-root-credentials"
type: Opaque
data:
  ROOT_DB_HOST: bXlzcWw=           # mysql
  ROOT_DB_USER: cm9vdA==           # root
  ROOT_DB_PASSWORD: cGFzc3dvcmQ=   # password
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-rabbitmq-admin
type: Opaque
data:
  RABBITMQ_CONNECTION: cmFiYml0Oi8vZ3Vlc3Q6Z3Vlc3RAcmFiYml0bXE6MTU2NzIvaXJvbmlj  # rabbit://guest:guest@rabbitmq:15672/ironic
---
apiVersion: v1
kind: Secret
metadata:
  name: ironic-rabbitmq-user
type: Opaque
data:
  RABBITMQ_CONNECTION: cmFiYml0Oi8vaXJvbmljOnBhc3N3b3JkQHJhYmJpdG1xOjE1NjcyL2lyb25pYw==  # rabbit://ironic:password@rabbitmq:15672/ironic
